version: '2'
services:
    avancement-app:
        image: avancement
        external_links:
            - avancement-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=avancement
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avancement-mongodb:
        extends:
            file: mongodb.yml
            service: avancement-mongodb
