version: '2'
services:
    avancement-mongodb:
        container_name: avancement-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb avancement-mongodb-config
    avancement-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    avancement-mongodb-config:
        image: mongo:3.2.10
        container_name: avancement-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
