version: '2'
services:
    avancement-mongodb:
        container_name: avancement-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/avancement/mongodb/:/data/db/
